dependencies:
  - jupyter-server-proxy==3.2.2
  - pandas==1.3.5
  - bokeh==2.4.2
  - Jinja2==3.0.3
  - MarkupSafe==2.0.1
  - numpy==1.22.1
  - packaging==21.3
  - Pillow==9.0.0
  - pyparsing==3.0.7
  - python-dateutil==2.8.2
  - pytz==2021.3
  - PyYAML==6.0
  - six==1.16.0
  - tornado==6.1
  - typing_extensions==4.0.1
  - pip