# constants:
avogadro = 6.022*10**23
kb = 1.3806*10**(-23)
echarge = 1.60217662 * 10**(-19)
thermal_voltage = kb*298/echarge

### Check: 48 elements (0-47) ###

label_with_unit = {'box_height': 'Box height / m',
 'colloid_height': 'Colloid height / m',
 'colloid_radius': 'Colloid radius / m',
 'conc': 'Concentration / mol m-3',
 'debye': 'Debye length / m',
 'tot_half_length': 'Total half length / m',
 'defect_length': 'Half length of defect / m',
 'temperature': 'Temperature / K',
 'surface_potential': 'Surface potential of surface / V',
 'defect_potential': 'Surface potential of defect / V',
 'particle_potential': 'Surface potential of particle / V',
 'def_sep': 'Separation between defect centers / m',
 'def_density': 'Local defect density',
 'def_height': 'Defect height / m',
 'def_num': 'Total defect number in a full unit cell',
 'biesheuvel_vol_int': 'Biesheuvel 2004 vol / kT m3',
 'krishnan_Uel_vol_int': 'Krishnan 2013 Uel vol part / kT m3',
 'krishnan_deltaS_vol_int': 'Krishnan 2013 deltaS vol part / kT m3 K-1',
 'particle_suf_int': 'Surface integral particle / J',
 'defect_suf_int': 'Surface integral defect / J',
 'whole_surface_suf_int': 'Surface integral whole surface / J',
 'total_potential': 'Total dimensionless surface potential',
 'total_area': 'Area of defects plus surface',
 'num_conc': 'Concentration / m-3',
 'colloid_height_debye': 'Colloid height = Colloid radius + x / Debye length',
 'rel_radius': 'Relative colloid radius (r/l_D)',
 'def_sep_lD': 'Defect separation/ l_D',
 'particle_potential_dless': 'Dimensionless particle potential',
 'defect_potential_dless': 'Dimensionless defect potential',
 'surface_potential_dless': 'Dimensionless surface potential',
 'average_surface_potential': 'Avearge dimensionless surface potential',
 'particle_suf_int_kT': 'Surface integral particle / kT',
 'defect_suf_int_kT': 'Surface integral defect / kT',
 'whole_suf_int_kT': 'Surface integral whole surface / kT',
 'krishnan_Uel_vol_term': 'Krishnan 2013 Uel volume contribution / kT',
 'krishnan_minusTdeltaS': 'Krishnan 2013 -T*deltaS / kT',
 'krishnan_vol_contribution': 'Krishnan 2013 volume contribution / kT',
 'particle_kT': 'Particle energy (delta E) / kT',
 'defect_kT': 'Defect energy (delta E) / kT',
 'defect_kT_fit': 'Defect energy fitted (delta E) / kT',
 'suf_kT': 'Normal surface energy (delta E) / kT',
 'suf_kT_fit': 'Normal surface energy fitted (delta E) / kT',
 'tot_surf_energy': 'Total surface energy / kT',
 'tot_vol_energy': 'Total volume energy / kT',
 'Fel': 'Krishnan 2013 interaction energy / kT',
 'hamaker': 'Hamaker constant / 10^-21 J',
 'vdw': 'van der Waals energy / kT',
 'totalE': 'Total intereaction energy / kT'}